# Generated by Django 4.2.5 on 2023-09-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_listing_curr_price_alter_bid_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='curr_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
